version: '3.7'
services:
  caddy:
    image: caddy:2
    container_name: caddy-mtls
    ports:
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/etc/caddy/certs
