version: '3.8'

services:
  certgen:
    build: .
    volumes:
      - ./certs:/app/certs
    # 持续运行容器，以便使用生成的证书
    command: tail -f /dev/null

  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./certs:/etc/ssl/selfsigned:ro
      - caddy_data:/data
      - caddy_config:/config

  backend:
    image: hashicorp/http-echo
    command: ["-text=Hello from backend"]
    expose:
      - "5678"

volumes:
  caddy_data:
  caddy_config:
