# This is a basic workflow to help you get started with Actions

name: CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Aliyun ACR
        run: |
          echo "${{ secrets.ALIYUN_PASSWORD }}" | docker login registry.cn-shanghai.aliyuncs.com \
            --username ${{ secrets.ALIYUN_USERNAME }} --password-stdin
            
      - name: Get current date
        id: date
        run: echo "tag=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      - name: Build and push Docker images to ACR
        run: |
          DATE_TAG=${{ steps.date.outputs.tag }}
          IMAGE_NAME=registry.cn-shanghai.aliyuncs.com/${{ secrets.ALIYUN_NAMESPACE }}/ssh-socks-proxy
          echo "Building and pushing $IMAGE_NAME:$DATE_TAG and $IMAGE_NAME:latest..."

          docker build -t $IMAGE_NAME:$DATE_TAG -t $IMAGE_NAME:latest ssh-socks-proxy
          docker push $IMAGE_NAME:$DATE_TAG
          docker push $IMAGE_NAME:latest


              
